import pandas as pd
import math
import os
from config import GROUPED_FOLDER, FILTERED_FOLDER, MIN_RR
from thresholds import generate_thresholds, fmt_threshold



def compute_score(df, threshold):
    total_trades = len(df)
    numeric_rr = pd.to_numeric(df["reward_risk"], errors="coerce")

    # Trades at or above threshold: +T each
    wins = numeric_rr >= threshold
    win_score = int(wins.sum()) * threshold

    # Positive trades below threshold: -1 each
    below_threshold = (numeric_rr > 0) & (numeric_rr < threshold)
    below_score = -int(below_threshold.sum())

    # Normal SL: -1 each
    sl_trades = df["reward_risk"] == "SL"
    sl_score = -int(sl_trades.sum())



    penalty = math.floor(total_trades / 10)

    score = win_score + below_score + sl_score - penalty
    return score


def write_manifest(files_by_threshold, manifest_path):
    """Write a threshold,filename manifest (one row per file per threshold)."""
    with open(manifest_path, "w") as f:
        f.write("threshold,filename\n")
        for T, files in files_by_threshold.items():
            for filename in files:
                f.write(f"{fmt_threshold(T)},{filename}\n")


def main():
    """
    Step 3 – Score and Filter.
    For each reward/risk threshold T, load each grouped CSV file,
    compute score, keep only files with score > 0.
    """
    # Ensure grouped folder exists
    if not os.path.exists(GROUPED_FOLDER):
        print(f"ERROR: {GROUPED_FOLDER} not found. Run step2_grouped.py first.")
        return

    # Determine thresholds from trades.csv (should be generated by step1)
    # If trades.csv not available, fallback to MIN_RR and a default range.
    # We'll compute thresholds similarly to step1_extract.py.
    if os.path.exists("trades.csv"):
        df_trades = pd.read_csv("trades.csv")
        numeric_rr = pd.to_numeric(df_trades["reward_risk"], errors="coerce")
        positive_rr = numeric_rr[numeric_rr >= MIN_RR]
        max_rr = positive_rr.max() if not positive_rr.empty else None
        thresholds = generate_thresholds(max_rr)
    else:
        thresholds = [float(MIN_RR)]  # default

    print(f"Thresholds: {thresholds}")

    # Ensure filtered folder exists
    os.makedirs(FILTERED_FOLDER, exist_ok=True)

    # Collect surviving and removed files per threshold
    surviving_files = {}
    removed_files = {}
    for T in thresholds:
        surviving = []
        removed = []
        # List all grouped CSV files
        for filename in os.listdir(GROUPED_FOLDER):
            if not filename.endswith(".csv"):
                continue
            filepath = os.path.join(GROUPED_FOLDER, filename)
            df = pd.read_csv(filepath)
            score = compute_score(df, T)
            if score > 0:
                surviving.append(filename)
                # Copy file to filtered subfolder (optional)
                subfolder = os.path.join(FILTERED_FOLDER, fmt_threshold(T))
                os.makedirs(subfolder, exist_ok=True)
                df.to_csv(os.path.join(subfolder, filename), index=False)
            else:
                # Removed distance bucket (score <= 0): recorded, not materialized
                removed.append(filename)
        surviving_files[T] = surviving
        removed_files[T] = removed
        print(f"Threshold {T}: {len(surviving)} surviving files, {len(removed)} removed")

    # Write manifests
    surviving_path = os.path.join(FILTERED_FOLDER, "surviving_files.csv")
    write_manifest(surviving_files, surviving_path)
    print(f"Manifest saved to {surviving_path}")

    removed_path = os.path.join(FILTERED_FOLDER, "removed_files.csv")
    write_manifest(removed_files, removed_path)
    print(f"Removed manifest saved to {removed_path}")


if __name__ == "__main__":
    main()